#!/usr/bin/env python3
"""Render Mission Cartography JSON into the bundled HTML template."""
from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def color_class(score: int, maximum: int) -> str:
    ratio = score / max(1, maximum)
    if ratio >= 0.75:
        return "good"
    if ratio >= 0.5:
        return "warn"
    return "bad"


def render_category_bars(categories: dict[str, dict[str, Any]]) -> str:
    rows: list[str] = []
    for key, category in categories.items():
        score = int(category.get("score", 0))
        maximum = int(category.get("max", 1))
        width = round(score / max(1, maximum) * 100)
        evidence = category.get("evidence", {})
        files = evidence.get("files", [])
        sub = f"{evidence.get('keyword_hits', 0)} signal hits"
        if files:
            sub += f" · {', '.join(files[:2])}"
        rows.append(
            '<div class="bar-row">'
            f'<div><div class="bar-label">{esc(key)}. {esc(category.get("name", ""))}</div><div class="bar-sub">{esc(sub)}</div></div>'
            f'<div class="track"><div class="fill {color_class(score, maximum)}" style="--w: {width}%"></div></div>'
            f'<div class="bar-score">{score}/{maximum}</div>'
            "</div>"
        )
    return "\n".join(rows)


def render_findings(report: dict[str, Any]) -> str:
    rows: list[str] = []
    for key, category in report.get("categories", {}).items():
        for finding in category.get("findings", [])[:2]:
            rows.append("<tr>" f'<td class="mono">{esc(key)}</td>' f"<td>{esc(finding)}</td>" "</tr>")
    if not rows:
        rows.append('<tr><td colspan="2">No material findings generated by the scanner.</td></tr>')
    return '<table><thead><tr><th>Cat</th><th>Finding</th></tr></thead><tbody>' + "\n".join(rows) + "</tbody></table>"


def render_actions(actions: list[dict[str, Any]]) -> str:
    rows: list[str] = []
    for action in actions[:8]:
        rows.append(
            "<tr>"
            f'<td class="mono">{esc(action.get("effort", ""))}</td>'
            f"<td>{esc(action.get('title', ''))}<br><span class=\"mono\">priority {esc(action.get('priority', ''))}</span></td>"
            f"<td>{esc(action.get('impact', ''))}</td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="3">No mission alignment actions generated.</td></tr>')
    return '<table><thead><tr><th>Effort</th><th>Action</th><th>Impact</th></tr></thead><tbody>' + "\n".join(rows) + "</tbody></table>"


def render_statements(report: dict[str, Any]) -> str:
    statements = report.get("extras", {}).get("mission_statements", [])
    if not statements:
        return "<p>No explicit mission-like statement was extracted.</p>"
    rows = [
        f'<li><span class="mono">{esc(item.get("path", ""))}</span>: {esc(item.get("statement", ""))}</li>'
        for item in statements[:5]
    ]
    return "<ul>" + "\n".join(rows) + "</ul>"


def evidence_notes(report: dict[str, Any]) -> str:
    meta = report.get("meta", {})
    extras = report.get("extras", {})
    notes = [
        f"Scanned {meta.get('files_total', 0)} files; extracted text from {meta.get('documents_scored', 0)} supported documents.",
        f"Mission-like statements found: {len(extras.get('mission_statements', []))}; evidence files: {len(extras.get('evidence_files', []))}.",
        f"Score mode: {meta.get('score_mode', 'heuristic baseline')}. Treat this as mission evidence review, not brand copywriting or investment advice.",
    ]
    failures = extras.get("extraction_failures", [])
    if failures:
        notes.append(f"Unreadable documents need OCR/export before scoring is reliable: {', '.join(failures[:5])}.")
    if extras.get("manual_review_required"):
        checks = extras.get("manual_review_checks", [])
        if checks:
            notes.append(f"Manual review required: {'; '.join(checks[:3])}.")
        else:
            notes.append("Manual review required before treating the score as confirmed.")
    return "\n".join(f"<li>{esc(note)}</li>" for note in notes)


def render(report: dict[str, Any], template: str) -> str:
    required = ["total", "grade", "categories", "actions", "meta"]
    missing = [key for key in required if key not in report]
    if missing:
        raise ValueError(f"missing required report fields: {', '.join(missing)}")
    meta = report.get("meta", {})
    insights = [item for item in report.get("insights", []) if item]
    summary = " ".join(insights) or "Heuristic mission baseline generated from available project evidence."
    replacements = {
        "{{PROJECT_NAME}}": esc(meta.get("project", "project")),
        "{{DATE}}": esc(meta.get("scored_at", "")),
        "{{FILE_COUNT}}": esc(meta.get("files_total", 0)),
        "{{DOC_COUNT}}": esc(meta.get("documents_scored", 0)),
        "{{SCORE_MODE}}": esc(meta.get("score_mode", "heuristic baseline")),
        "{{TOTAL}}": esc(report.get("total", 0)),
        "{{GRADE}}": esc(report.get("grade", "Unknown")),
        "{{SUMMARY}}": esc(summary),
        "{{CATEGORY_BARS}}": render_category_bars(report.get("categories", {})),
        "{{FINDINGS_TABLE}}": render_findings(report),
        "{{ACTIONS_TABLE}}": render_actions(report.get("actions", [])),
        "{{MISSION_STATEMENTS}}": render_statements(report),
        "{{EVIDENCE_NOTES}}": evidence_notes(report),
    }
    output = template
    for placeholder, value in replacements.items():
        output = output.replace(placeholder, value)
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("score_json")
    parser.add_argument("--template", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    report = json.loads(Path(args.score_json).read_text(encoding="utf-8"))
    template = Path(args.template).read_text(encoding="utf-8")
    output = render(report, template)
    if "{{" in output or "}}" in output:
        raise SystemExit("unresolved template placeholder remains")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
